### ISSUE TITLE
Where are the specification of mini/microKanren's each function ?

### ISSUE THREAD

**Issue by Cartman0** [miniKanren/miniKanren_org-website#30]
Hi.
I'm looking for the specification of mini/microKanren's each function.
where are there?

**Comment by jasonhemann** [comment]
Howdy. Are you asking for an equivalent of a Prolog iteration construct (e.g. `foreach/2`?)

**Comment by Cartman0** [comment]
yes, I want to see the definition such as `membro/2` not only Prolog iteration on mini/microKanren DSL.

**Comment by jasonhemann** [comment]
Many of these functions are defined as user-level programs in TRS, TRS2/e. We have not built many of those higher-order goals, since they cannot be fully relational, and run in all modes, inverted. When I have wanted that behavior, for convenience, I've often employed a host-language macro to generate the first-order relation.

**Comment by Cartman0** [comment]
@jasonhemann 
ok, thanks. where are function's specification are as defined core-level programs? 
only your microKanren paper([µKanren: A Minimal Functional Core
for Relational Programming](http://webyrd.net/scheme-2013/papers/HemannMuKanren2013.pdf))?

**Comment by jasonhemann** [comment]
Many of these aren't explicit, enforced language restrictions. I've heard from people who appreciate that a shallow embedding allows them all manner of interaction with the host language. 

But I think yes, that and https://dl.acm.org/doi/abs/10.1145/2989225.2989230

**Comment by Cartman0** [comment]
@jasonhemann 
thanks for info. I saw should learn Scheme's core-level interface.
If it's possible, I would like want easy interface list later.
